columns:
- NACCNURP: int
- NACCNRYR: int
- NACCREAS: int
- NACCREFR: int
- BIRTHMO: int
- BIRTHYR: int
- SEX: int
- HISPANIC: int
- HISPOR: int
- HISPORX: object
- RACE: int
- RACEX: object
- RACESEC: int
- RACESECX: object
- RACETER: int
- RACETERX: object
- PRIMLANG: int
- PRIMLANX: object
- EDUC: int
- MARISTAT: int
- NACCLIVS: int
- INDEPEND: int
- RESIDENC: int
- HANDED: int
- NACCAGE: int
- NACCAGEB: int
- NACCNIHR: int
- DEMENTED: int
- NACCFAM: int
- NACCMOM: int
- NACCDAD: int
- ANYMEDS: int
- NACCAMD: int
- NACCAHTN: int
- NACCHTNC: int
- NACCACEI: int
- NACCAAAS: int
- NACCBETA: int
- NACCCCBS: int
- NACCDIUR: int
- NACCVASD: int
- NACCANGI: int
- NACCLIPL: int
- NACCNSD: int
- NACCAC: int
- NACCADEP: int
- NACCAPSY: int
- NACCAANX: int
- NACCADMD: int
- NACCPDMD: int
- NACCEMD: int
- NACCEPMD: int
- NACCDBMD: int
- DRUG1: object
- DRUG2: object
- DRUG3: object
- DRUG4: object
- DRUG5: object
- DRUG6: object
- DRUG7: object
- DRUG8: object
- DRUG9: object
- DRUG10: object
- DRUG11: object
- DRUG12: object
- DRUG13: object
- DRUG14: object
- DRUG15: object
- DRUG16: object
- DRUG17: object
- DRUG18: object
- DRUG19: object
- DRUG20: object
- DRUG21: object
- DRUG22: object
- DRUG23: object
- DRUG24: object
- DRUG25: object
- DRUG26: object
- DRUG27: float
- DRUG28: float
- DRUG29: float
- DRUG30: float
- DRUG31: float
- DRUG32: float
- DRUG33: float
- DRUG34: float
- DRUG35: float
- DRUG36: float
- DRUG37: float
- DRUG38: float
- DRUG39: float
- DRUG40: float
- TOBAC30: int
- TOBAC100: int
- SMOKYRS: int
- PACKSPER: int
- QUITSMOK: int
- ALCOCCAS: int
- ALCFREQ: int
- CVHATT: int
- HATTMULT: int
- HATTYEAR: int
- CVAFIB: int
- CVANGIO: int
- CVBYPASS: int
- CVPACDEF: int
- CVPACE: int
- CVCHF: int
- CVANGINA: int
- CVHVALVE: int
- CVOTHR: int
- CVOTHRX: object
- CBSTROKE: int
- STROKMUL: int
- NACCSTYR: int
- CBTIA: int
- TIAMULT: int
- NACCTIYR: int
- PD: int
- PDYR: int
- PDOTHR: int
- PDOTHRYR: int
- SEIZURES: int
- TBI: int
- TBIBRIEF: int
- TRAUMBRF: int
- TBIEXTEN: int
- TRAUMEXT: int
- TBIWOLOS: int
- TRAUMCHR: int
- TBIYEAR: int
- NCOTHR: int
- NCOTHRX: float
- DIABETES: int
- DIABTYPE: int
- HYPERTEN: int
- HYPERCHO: int
- B12DEF: int
- THYROID: int
- ARTHRIT: int
- ARTHTYPE: int
- ARTHTYPX: object
- ARTHUPEX: int
- ARTHLOEX: int
- ARTHSPIN: int
- ARTHUNK: int
- INCONTU: int
- INCONTF: int
- APNEA: int
- RBD: int
- INSOMN: int
- OTHSLEEP: int
- OTHSLEEX: object
- ALCOHOL: int
- ABUSOTHR: int
- ABUSX: object
- PTSD: int
- BIPOLAR: int
- SCHIZ: int
- DEP2YRS: int
- DEPOTHR: int
- ANXIETY: int
- OCD: int
- NPSYDEV: int
- PSYCDIS: int
- PSYCDISX: object
- NACCTBI: int
- HEIGHT: float
- WEIGHT: float
- NACCBMI: float
- VISION: int
- VISCORR: int
- VISWCORR: int
- HEARING: int
- HEARAID: int
- HEARWAID: int
- DEL: int
- DELSEV: int
- HALL: int
- HALLSEV: int
- AGIT: int
- AGITSEV: int
- DEPD: int
- DEPDSEV: int
- ANX: int
- ANXSEV: int
- ELAT: int
- ELATSEV: int
- APA: int
- APASEV: int
- DISN: int
- DISNSEV: int
- IRR: int
- IRRSEV: int
- MOT: int
- MOTSEV: int
- NITE: int
- NITESEV: int
- APP: int
- APPSEV: int
- SATIS: int
- DROPACT: int
- EMPTY: int
- BORED: int
- SPIRITS: int
- AFRAID: int
- HAPPY: int
- HELPLESS: int
- STAYHOME: int
- MEMPROB: int
- WONDRFUL: int
- WRTHLESS: int
- ENERGY: int
- HOPELESS: int
- BETTER: int
- BILLS: int
- TAXES: int
- SHOPPING: int
- GAMES: int
- STOVE: int
- MEALPREP: int
- EVENTS: int
- PAYATTN: int
- REMDATES: int
- TRAVEL: int
- DECSUB: int
- DECIN: int
numerical_columns:
- NACCNURP
- NACCNRYR
- NACCREAS
- NACCREFR
- BIRTHMO
- BIRTHYR
- SEX
- HISPANIC
- HISPOR
- RACE
- RACESEC
- RACETER
- PRIMLANG
- EDUC
- MARISTAT
- NACCLIVS
- INDEPEND
- RESIDENC
- HANDED
- NACCAGE
- NACCAGEB
- NACCNIHR
- DEMENTED
- NACCFAM
- NACCMOM
- NACCDAD
- ANYMEDS
- NACCAMD
- NACCAHTN
- NACCHTNC
- NACCACEI
- NACCAAAS
- NACCBETA
- NACCCCBS
- NACCDIUR
- NACCVASD
- NACCANGI
- NACCLIPL
- NACCNSD
- NACCAC
- NACCADEP
- NACCAPSY
- NACCAANX
- NACCADMD
- NACCPDMD
- NACCEMD
- NACCEPMD
- NACCDBMD
- DRUG27
- DRUG28
- DRUG29
- DRUG30
- DRUG31
- DRUG32
- DRUG33
- DRUG34
- DRUG35
- DRUG36
- DRUG37
- DRUG38
- DRUG39
- DRUG40
- TOBAC30
- TOBAC100
- SMOKYRS
- PACKSPER
- QUITSMOK
- ALCOCCAS
- ALCFREQ
- CVHATT
- HATTMULT
- HATTYEAR
- CVAFIB
- CVANGIO
- CVBYPASS
- CVPACDEF
- CVPACE
- CVCHF
- CVANGINA
- CVHVALVE
- CVOTHR
- CBSTROKE
- STROKMUL
- NACCSTYR
- CBTIA
- TIAMULT
- NACCTIYR
- PD
- PDYR
- PDOTHR
- PDOTHRYR
- SEIZURES
- TBI
- TBIBRIEF
- TRAUMBRF
- TBIEXTEN
- TRAUMEXT
- TBIWOLOS
- TRAUMCHR
- TBIYEAR
- NCOTHR
- NCOTHRX
- DIABETES
- DIABTYPE
- HYPERTEN
- HYPERCHO
- B12DEF
- THYROID
- ARTHRIT
- ARTHTYPE
- ARTHUPEX
- ARTHLOEX
- ARTHSPIN
- ARTHUNK
- INCONTU
- INCONTF
- APNEA
- RBD
- INSOMN
- OTHSLEEP
- ALCOHOL
- ABUSOTHR
- PTSD
- BIPOLAR
- SCHIZ
- DEP2YRS
- DEPOTHR
- ANXIETY
- OCD
- NPSYDEV
- PSYCDIS
- NACCTBI
- HEIGHT
- WEIGHT
- NACCBMI
- VISION
- VISCORR
- VISWCORR
- HEARING
- HEARAID
- HEARWAID
- DEL
- DELSEV
- HALL
- HALLSEV
- AGIT
- AGITSEV
- DEPD
- DEPDSEV
- ANX
- ANXSEV
- ELAT
- ELATSEV
- APA
- APASEV
- DISN
- DISNSEV
- IRR
- IRRSEV
- MOT
- MOTSEV
- NITE
- NITESEV
- APP
- APPSEV
- SATIS
- DROPACT
- EMPTY
- BORED
- SPIRITS
- AFRAID
- HAPPY
- HELPLESS
- STAYHOME
- MEMPROB
- WONDRFUL
- WRTHLESS
- ENERGY
- HOPELESS
- BETTER
- BILLS
- TAXES
- SHOPPING
- GAMES
- STOVE
- MEALPREP
- EVENTS
- PAYATTN
- REMDATES
- TRAVEL
- DECSUB
- DECIN
